Issue 12: Add checking of Python code
Componolit/RecordFlux-specifications pull request #14
Opened 2020-12-01 15:04 UTC by treiher

Closes #12

2020-12-01 17:26 UTC, jklmnn approved these changes

2020-12-01 20:52 UTC, senier requested changes

2020-12-01 20:52 UTC, senier commented on .isort.cfg
> +known_third_party=gi,icontract,pydotplus,pyparsing,pytest,z3
Do we need (all of) those?

2020-12-03 09:09 UTC, treiher commented on .isort.cfg
> +known_third_party=gi,icontract,pydotplus,pyparsing,pytest,z3
Probably not, I have removed them.

2020-12-03 09:12 UTC, senier approved these changes

2020-12-03 09:25 UTC, jklmnn approved these changes

2020-12-03 10:13 UTC, merged