Issue 80: Support parameterized messages in validation tool
Componolit/RecordFlux-specifications pull request #91
Opened 2021-09-29 13:17 UTC by jklmnn

ref #80

2021-09-29 16:20 UTC, treiher requested changes

2021-09-30 09:29 UTC, jklmnn commented on tls_heartbeat.rflx
> +            if TLS_Plaintext_Length >= Payload_Length + 3;
Fixed in https://github.com/Componolit/RecordFlux-specifications/pull/91/commits/afef1964c6261fe8715b2578044c4ce61f6b4cbf.

2021-09-30 09:39 UTC, senier approved these changes

2021-09-30 14:02 UTC, treiher requested changes

2021-09-30 14:02 UTC, treiher commented on tls_heartbeat.rflx
> +               and Padding'Size >= 16;
- The check of the padding size is wrong, should be: `Padding'Size / 8 >= 16`.
- I think the size aspect would be easier like this: `(TLS_Plaintext_Length - Payload_Length) * 8 - Message_Type'Size - Payload_Length'Size`.

2021-09-30 16:26 UTC, treiher approved these changes

2021-09-30 16:27 UTC, merged